version: '3,9'

services:
  client1:
    container_name: client1
    build:
      context: ./reseau/client1
      dockerfile: Dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.2

  client2:
    container_name: client2
    build:
      context: ./reseau/client2
      dockerfile: Dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.3

  pirate:
    container_name: pirate
    build:
      context: ./reseau/pirate
      dockerfile: Dockerfile
    privileged: true
    networks:
      my_network:
        ipv4_address: 192.168.1.4

networks:
  my_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_forward: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24